version: "3"

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn --certfile=/etc/certs/localhost.crt --keyfile=/etc/certs/localhost.key hello_earth.wsgi:application --bind 0.0.0.0:443"
    container_name: hola_mundo
    env_file:
      - ./config/web/web-variables.env
    volumes:
      - ./code:/src
      - ./config/nginx/certs/:/etc/certs
    expose:
      - "443"
  
  nginx:
    image: nginx:latest
    container_name: ng
    ports:
      - "1443:443"
      - "1080:80"
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d
    depends_on:
      - web